/******************************************************************************
Project         : RideNow Enterprise Data Platform
Module          : Bronze Layer
Object          : PAYMENT_RAW
Object Type     : Table
Schema          : BRONZE
Script          : 07_Create_Payment_RAW.sql
Author          : Manmeet Singh
Version         : 1.0
Environment     : DEV
Created Date    : 15-Jul-2026

Description:
Creates the PAYMENT_RAW table in the BRONZE schema.
Stores payment transaction data exactly as received from the source system.

------------------------------------------------------------------------------
Load Pattern
------------------------------------------------------------------------------
Source File     : payment.csv
Load Type       : Full Load
Refresh         : Daily
Target Layer    : Bronze
Source Format   : CSV

------------------------------------------------------------------------------
Dependencies
------------------------------------------------------------------------------
Input File      : payment.csv
Target Table    : BRONZE.PAYMENT_RAW
Downstream      : SILVER.FACT_PAYMENT
******************************************************************************/

--==============================================================================
-- Step 1 : Set Context
--==============================================================================

USE ROLE ROLE_ADMIN;

USE WAREHOUSE WH_ETL;

USE DATABASE RIDENOW_DB;

USE SCHEMA BRONZE;

--==============================================================================
-- Step 2 : Create PAYMENT_RAW Table
--==============================================================================

CREATE OR REPLACE TRANSIENT TABLE PAYMENT_RAW
(
    ----------------------------------------------------------------------------
    -- Business Columns
    ----------------------------------------------------------------------------

    PAYMENT_ID                  VARCHAR(20),
    TRIP_ID                     VARCHAR(20),
    CUSTOMER_ID                 VARCHAR(20),

    PAYMENT_METHOD              VARCHAR(30),
    PAYMENT_PROVIDER            VARCHAR(50),
    TRANSACTION_REFERENCE       VARCHAR(50),

    PAYMENT_AMOUNT              NUMBER(10,2),

    PAYMENT_TIMESTAMP           TIMESTAMP_NTZ,

    PAYMENT_STATUS              VARCHAR(20),

    ----------------------------------------------------------------------------
    -- Metadata Columns
    ----------------------------------------------------------------------------

    LOAD_TIMESTAMP              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME            VARCHAR(255),
    SOURCE_SYSTEM               VARCHAR(50),
    BATCH_ID                    NUMBER(38,0),
    ROW_NUMBER                  NUMBER(38,0)

);

--==============================================================================
-- Step 3 : Table Comment
--==============================================================================

COMMENT ON TABLE PAYMENT_RAW IS
'Stores raw payment transaction data exactly as received from the source system.';

--==============================================================================
-- Step 4 : Column Comments
--==============================================================================

COMMENT ON COLUMN PAYMENT_RAW.PAYMENT_ID
IS 'Business identifier received from the source system.';

COMMENT ON COLUMN PAYMENT_RAW.TRIP_ID
IS 'Trip identifier associated with the payment.';

COMMENT ON COLUMN PAYMENT_RAW.CUSTOMER_ID
IS 'Customer identifier associated with the payment.';

COMMENT ON COLUMN PAYMENT_RAW.PAYMENT_METHOD
IS 'Payment method used by the customer.';

COMMENT ON COLUMN PAYMENT_RAW.PAYMENT_PROVIDER
IS 'Payment provider or card network used for the transaction.';

COMMENT ON COLUMN PAYMENT_RAW.TRANSACTION_REFERENCE
IS 'Unique transaction reference generated by the payment provider.';

COMMENT ON COLUMN PAYMENT_RAW.PAYMENT_AMOUNT
IS 'Payment amount received from the customer.';

COMMENT ON COLUMN PAYMENT_RAW.PAYMENT_TIMESTAMP
IS 'Timestamp when the payment was completed.';

COMMENT ON COLUMN PAYMENT_RAW.PAYMENT_STATUS
IS 'Current payment status received from the source system.';

COMMENT ON COLUMN PAYMENT_RAW.LOAD_TIMESTAMP
IS 'Timestamp when the record was loaded into the Bronze layer.';

COMMENT ON COLUMN PAYMENT_RAW.SOURCE_FILE_NAME
IS 'Source CSV file name.';

COMMENT ON COLUMN PAYMENT_RAW.SOURCE_SYSTEM
IS 'Originating source application.';

COMMENT ON COLUMN PAYMENT_RAW.BATCH_ID
IS 'ETL Batch Identifier.';

COMMENT ON COLUMN PAYMENT_RAW.ROW_NUMBER
IS 'Row number from the source file.';

--==============================================================================
-- Step 5 : Verification
--==============================================================================

DESC TABLE PAYMENT_RAW;

SHOW TABLES LIKE 'PAYMENT_RAW';

--==============================================================================
-- End of Script
--==============================================================================
